services:
  treehealth:
    build:
      context: .
      dockerfile: Dockerfile.cpu
    image: treehealth-cpu:latest
    container_name: tree-health-infer-service-treehealth-1
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
      - ./weights:/weights
      - ./rules:/rules
    restart: unless-stopped
