version: "3.9"
services:
  treehealth:
    build:
      context: .
      dockerfile: Dockerfile.cpu
    image: treehealth-cpu:latest
    env_file: .env
    volumes:
      - ./weights:/weights
      - ./data:/data
      - ./rules:/rules
    ports:
      - "8000:8000"
    command: >
          gunicorn app.main:app -k uvicorn.workers.UvicornWorker
          --bind 0.0.0.0:8000 --workers 1 --timeout 3000
