FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

# НУЖЕН git для torch.hub (MiDaS)
RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /srv/app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN useradd -ms /bin/bash appuser && chown -R appuser:appuser /srv/app
USER appuser

EXPOSE 8000
CMD ["gunicorn","-k","uvicorn.workers.UvicornWorker","--workers","1","--timeout","120","--bind","0.0.0.0:8000","app.main:app"]